import type { EndgameLesson } from './types';

export const endgameLessons: EndgameLesson[] = [
  // ---------------------------------------------------------------------------
  // ESSENTIAL CHECKMATES
  // ---------------------------------------------------------------------------
  {
    id: 'king-queen-vs-king',
    kind: 'endgame',
    name: 'King + Queen vs King',
    category: 'Essential Checkmates',
    difficulty: 'beginner',
    description:
      'The simplest forced checkmate. The queen alone can restrict the enemy king to progressively smaller rectangles of the board (the "shrinking box"), but checkmate requires your king to assist by controlling escape squares. The main danger is stalemate — always verify the enemy king has at least one legal move before closing in.',
    startingFen: '4k3/8/8/8/8/8/8/4K2Q w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'Qd5', explanation: 'Centralize the queen — from d5 she controls the center and starts building a wall that confines the black king.', playedBy: 'user' },
      { moveSan: 'Kf8', explanation: 'Black retreats toward the edge, which is exactly what we want.', playedBy: 'auto' },
      { moveSan: 'Qd7', explanation: 'Shrink the box — the queen now cuts off the 7th rank, confining the king to the back rank.', playedBy: 'user' },
      { moveSan: 'Kg8', explanation: 'Black is forced along the 8th rank.', playedBy: 'auto' },
      { moveSan: 'Kf2', explanation: 'Start advancing the king. The queen cannot deliver checkmate alone — your king must help control escape squares.', playedBy: 'user' },
      { moveSan: 'Kf8', explanation: 'Black oscillates, hoping we stalemate.', playedBy: 'auto' },
      { moveSan: 'Ke3', explanation: 'Keep marching the king forward purposefully. Every tempo counts in the endgame.', playedBy: 'user' },
      { moveSan: 'Kg8', explanation: 'Black has little choice with the queen covering d7.', playedBy: 'auto' },
      { moveSan: 'Ke4', explanation: 'Continue advancing. The king needs to reach the 6th rank to assist the queen in delivering mate.', playedBy: 'user' },
      { moveSan: 'Kf8', explanation: 'Black shuffles back.', playedBy: 'auto' },
      { moveSan: 'Ke5', explanation: 'One more step — the king approaches the 6th rank.', playedBy: 'user' },
      { moveSan: 'Kg8', explanation: 'Black returns to g8.', playedBy: 'auto' },
      { moveSan: 'Ke6', explanation: 'The king reaches the 6th rank. Now we can coordinate the final mating pattern.', playedBy: 'user' },
      { moveSan: 'Kh8', explanation: 'Black retreats to the corner — the last refuge.', playedBy: 'auto' },
      { moveSan: 'Kf7', explanation: 'Close in with the king, taking away g8 and g7 as escape routes.', playedBy: 'user' },
      { moveSan: 'Kh7', explanation: 'Black is forced to h7 — the only available square.', playedBy: 'auto' },
      { moveSan: 'Qd8', explanation: 'Prepare the mating net. The queen controls the 8th rank and h4-d8 diagonal.', playedBy: 'user' },
      { moveSan: 'Kh6', explanation: 'The king tries to escape down the h-file.', playedBy: 'auto' },
      { moveSan: 'Qh4#', explanation: 'Checkmate! The king is on the edge with no escape — the queen delivers mate from h4 while our king controls g6 and g7.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'Use the "shrinking box" method — the queen restricts the king to progressively smaller rectangles',
      'The queen cannot deliver checkmate alone — advance your king to help control escape squares',
      'Always check for stalemate before moving the queen close to the enemy king',
      'Forced mate in at most 10 moves with optimal play from any starting position',
    ],
  },

  {
    id: 'king-rook-vs-king',
    kind: 'endgame',
    name: 'King + Rook vs King (Box Method)',
    category: 'Essential Checkmates',
    difficulty: 'beginner',
    description:
      'The rook is less powerful than the queen, so this checkmate requires more coordination between your king and rook. The "box method" works by placing the rook on a rank or file to create a barrier the enemy king cannot cross, then using your king to gain opposition and push the enemy king back rank by rank until checkmate on the edge.',
    startingFen: '4k3/8/8/8/8/8/8/R3K3 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'Ra5', explanation: 'Cut off the king — the rook creates a wall along the 5th rank. The black king can no longer cross below this line.', playedBy: 'user' },
      { moveSan: 'Kd7', explanation: 'Black tries to stay centralized, but the box is already shrinking.', playedBy: 'auto' },
      { moveSan: 'Kd2', explanation: 'Begin advancing the king. The rook holds the barrier while your king marches up to gain opposition.', playedBy: 'user' },
      { moveSan: 'Kd6', explanation: 'Black steps toward the rook — if it gets too close, the rook shifts.', playedBy: 'auto' },
      { moveSan: 'Kd3', explanation: 'Continue advancing steadily.', playedBy: 'user' },
      { moveSan: 'Ke6', explanation: 'Black tries to stay near the center.', playedBy: 'auto' },
      { moveSan: 'Ke4', explanation: 'Your king opposes Black\'s king — now when the black king moves, the rook can shrink the box.', playedBy: 'user' },
      { moveSan: 'Kf6', explanation: 'Black steps aside, breaking opposition.', playedBy: 'auto' },
      { moveSan: 'Ra6+', explanation: 'Check! Push the king back one rank. This is the key pattern — gain opposition, then check with the rook to shrink the box.', playedBy: 'user' },
      { moveSan: 'Kf7', explanation: 'Forced back to the 7th rank.', playedBy: 'auto' },
      { moveSan: 'Kf5', explanation: 'Follow up — get your king to the 5th rank so you can gain opposition again on the next cycle.', playedBy: 'user' },
      { moveSan: 'Ke7', explanation: 'Black attempts to centralize again on the 7th rank.', playedBy: 'auto' },
      { moveSan: 'Ke5', explanation: 'Opposition achieved again — kings face off with one rank between them.', playedBy: 'user' },
      { moveSan: 'Kd7', explanation: 'Black must yield.', playedBy: 'auto' },
      { moveSan: 'Ra7+', explanation: 'Push the king to the 8th rank — now the box is as small as it gets.', playedBy: 'user' },
      { moveSan: 'Kd8', explanation: 'Forced to the back rank.', playedBy: 'auto' },
      { moveSan: 'Ke6', explanation: 'Advance the king to the 6th rank with opposition on d6 next.', playedBy: 'user' },
      { moveSan: 'Ke8', explanation: 'Black faces the king on the same file.', playedBy: 'auto' },
      { moveSan: 'Ra8#', explanation: 'Checkmate on the back rank! Your king controls d7, e7, and f7 — the rook delivers the final blow.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'The rook creates a wall (rank or file) the enemy king cannot cross',
      'Your king must actively participate — the rook cannot do it alone',
      'Gain opposition (kings facing, one square apart), then check with the rook to push the enemy king back one rank',
      'Watch for stalemate in the corner — always leave one escape square before the final check',
      'Forced mate in at most 16 moves from any starting position',
    ],
  },

  {
    id: 'king-two-bishops-vs-king',
    kind: 'endgame',
    name: 'King + 2 Bishops vs King',
    category: 'Essential Checkmates',
    difficulty: 'advanced',
    description:
      'Two bishops complement each other perfectly — one controls light squares, the other dark squares. Together they create an impassable diagonal wall. The technique involves centralizing your pieces, building diagonal barriers that form a shrinking "V" shape, and driving the enemy king to any corner for checkmate. Unlike bishop+knight, two bishops can force mate in any corner.',
    startingFen: '4k3/8/8/8/8/8/8/2B1KB2 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'Bd2', explanation: 'Develop the dark-squared bishop. We need both bishops active before advancing.', playedBy: 'user' },
      { moveSan: 'Kd7', explanation: 'Black moves centrally.', playedBy: 'auto' },
      { moveSan: 'Bd3', explanation: 'Develop the light-squared bishop toward the center. Both bishops on adjacent diagonals will create a funnel.', playedBy: 'user' },
      { moveSan: 'Ke7', explanation: 'Black tries to stay central.', playedBy: 'auto' },
      { moveSan: 'Ke2', explanation: 'Advance the king. All three pieces need to work together — the king seals off escape routes the bishops cannot.', playedBy: 'user' },
      { moveSan: 'Kd6', explanation: 'Black maneuvers in the center.', playedBy: 'auto' },
      { moveSan: 'Be4', explanation: 'The light-squared bishop takes a long diagonal, aiming at the queenside. The diagonal wall starts forming.', playedBy: 'user' },
      { moveSan: 'Ke7', explanation: 'Black retreats.', playedBy: 'auto' },
      { moveSan: 'Be3', explanation: 'The dark-squared bishop covers the adjacent diagonal. Together they control a diagonal barrier the king cannot cross.', playedBy: 'user' },
      { moveSan: 'Kd6', explanation: 'Black tries to step forward but the bishops limit options.', playedBy: 'auto' },
      { moveSan: 'Kd3', explanation: 'The king continues advancing to support the mating net.', playedBy: 'user' },
      { moveSan: 'Ke7', explanation: 'Black shuffles.', playedBy: 'auto' },
      { moveSan: 'Bf4', explanation: 'Advance the barrier — the bishops tighten the diagonal wall, pushing the king toward the edge.', playedBy: 'user' },
      { moveSan: 'Kd7', explanation: 'Black drifts toward the corner.', playedBy: 'auto' },
      { moveSan: 'Bf5+', explanation: 'Check forces the king closer to the corner. The diagonal barrier is now very tight.', playedBy: 'user' },
      { moveSan: 'Ke7', explanation: 'Black retreats.', playedBy: 'auto' },
      { moveSan: 'Ke4', explanation: 'Keep the king advancing in coordination.', playedBy: 'user' },
      { moveSan: 'Kf8', explanation: 'Black retreats toward the corner — exactly what we want.', playedBy: 'auto' },
      { moveSan: 'Ke5', explanation: 'Continue closing in.', playedBy: 'user' },
      { moveSan: 'Kg7', explanation: 'Black tries to escape via g7.', playedBy: 'auto' },
      { moveSan: 'Be6', explanation: 'Control f7 and the diagonal — the king is being herded to the corner.', playedBy: 'user' },
      { moveSan: 'Kf8', explanation: 'Back to f8.', playedBy: 'auto' },
      { moveSan: 'Kf6', explanation: 'Opposition on the 6th rank — the net tightens.', playedBy: 'user' },
      { moveSan: 'Ke8', explanation: 'Forced to the back rank.', playedBy: 'auto' },
      { moveSan: 'Bg6+', explanation: 'Check from the light-squared bishop drives the king into the corner.', playedBy: 'user' },
      { moveSan: 'Kf8', explanation: 'Forced.', playedBy: 'auto' },
      { moveSan: 'Be5', explanation: 'Seal off g7 and the dark squares — the king is trapped in the corner.', playedBy: 'user' },
      { moveSan: 'Ke8', explanation: 'The only legal move.', playedBy: 'auto' },
      { moveSan: 'Bf5', explanation: 'Prepare the final mating pattern — control the key light squares.', playedBy: 'user' },
      { moveSan: 'Kf8', explanation: 'Forced back.', playedBy: 'auto' },
      { moveSan: 'Bd6#', explanation: 'Checkmate! The dark-squared bishop delivers mate. The light bishop and king control every escape square.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'Two bishops control all 64 squares together — their diagonal barriers are impassable',
      'Build a "V"-shaped funnel with both bishops on adjacent diagonals',
      'Checkmate can be forced in any corner (unlike bishop+knight)',
      'The king must actively participate — it seals off escape routes the bishops miss',
      'Watch for stalemate when the enemy king is cornered',
      'Forced mate in at most 19 moves from any position',
    ],
  },

  {
    id: 'king-bishop-knight-vs-king',
    kind: 'endgame',
    name: 'King + Bishop + Knight vs King',
    category: 'Essential Checkmates',
    difficulty: 'advanced',
    description:
      'The hardest basic checkmate — even grandmasters have failed it in tournament play. The difficulty comes from the bishop and knight having very different movement patterns. Checkmate can only be forced in a corner matching the bishop\'s square color. The technique has three phases: drive the king to the edge, redirect it to the correct corner (using the W-maneuver if necessary), and deliver mate. Must complete within the 50-move rule.',
    startingFen: '4k3/8/8/8/8/8/8/1N2KB2 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'Nd2', explanation: 'Centralize the knight. Both minor pieces need to coordinate toward the center before we can start restricting the enemy king.', playedBy: 'user' },
      { moveSan: 'Kd7', explanation: 'Black tries to stay central.', playedBy: 'auto' },
      { moveSan: 'Bg2', explanation: 'Develop the bishop to a long diagonal. This light-squared bishop means we must force the king to a light corner (a8 or h1).', playedBy: 'user' },
      { moveSan: 'Ke7', explanation: 'Black maneuvers.', playedBy: 'auto' },
      { moveSan: 'Ke2', explanation: 'Advance the king. All three pieces must cooperate in this endgame.', playedBy: 'user' },
      { moveSan: 'Kd6', explanation: 'Black stays central.', playedBy: 'auto' },
      { moveSan: 'Nf3', explanation: 'The knight heads to the center. From f3 it controls e5, d4, g5 — key central squares.', playedBy: 'user' },
      { moveSan: 'Ke7', explanation: 'Black shuffles.', playedBy: 'auto' },
      { moveSan: 'Ke3', explanation: 'Phase 1: Push the king toward the edge. Our three pieces gradually restrict Black\'s options.', playedBy: 'user' },
      { moveSan: 'Kf6', explanation: 'Black tries to flee toward the kingside.', playedBy: 'auto' },
      { moveSan: 'Nd4', explanation: 'The knight leaps to d4, controlling e6, f5, c6, b5 — blocking retreat paths.', playedBy: 'user' },
      { moveSan: 'Kg5', explanation: 'Black heads toward the edge.', playedBy: 'auto' },
      { moveSan: 'Bf3', explanation: 'The bishop shifts to control g4 and h5, preventing the king from escaping along the edge.', playedBy: 'user' },
      { moveSan: 'Kf6', explanation: 'The king tries to come back to the center.', playedBy: 'auto' },
      { moveSan: 'Ne6', explanation: 'The knight lands on e6, controlling key squares and pushing the king toward the h8 corner.', playedBy: 'user' },
      { moveSan: 'Kg7', explanation: 'Black retreats.', playedBy: 'auto' },
      { moveSan: 'Kf4', explanation: 'Phase 2: Direct the king toward the correct corner (h1, a light square). The W-maneuver redirects from h8 if needed.', playedBy: 'user' },
      { moveSan: 'Kf6', explanation: 'Black resists.', playedBy: 'auto' },
      { moveSan: 'Nd4', explanation: 'The knight repositions — controlling the key squares needed to wall off the king.', playedBy: 'user' },
      { moveSan: 'Kg7', explanation: 'Black drifts back.', playedBy: 'auto' },
      { moveSan: 'Kg5', explanation: 'Our king closes in. The mating net is forming.', playedBy: 'user' },
      { moveSan: 'Kh8', explanation: 'Black reaches the wrong corner (h8 is dark). We must now use the W-maneuver to redirect.', playedBy: 'auto' },
      { moveSan: 'Nf5', explanation: 'The knight begins the W-maneuver — controlling g7 to keep the king trapped.', playedBy: 'user' },
      { moveSan: 'Kg8', explanation: 'Forced.', playedBy: 'auto' },
      { moveSan: 'Be4', explanation: 'The bishop controls h7 — the king cannot return to the corner.', playedBy: 'user' },
      { moveSan: 'Kf8', explanation: 'Black tries to escape along the back rank.', playedBy: 'auto' },
      { moveSan: 'Kf6', explanation: 'Our king cuts off escape toward the center.', playedBy: 'user' },
      { moveSan: 'Ke8', explanation: 'Black continues along the edge, being redirected toward a8.', playedBy: 'auto' },
      { moveSan: 'Nd6+', explanation: 'Phase 3: The knight checks, driving the king toward a8 — the correct light-square corner.', playedBy: 'user' },
      { moveSan: 'Kd8', explanation: 'Forced toward the queenside.', playedBy: 'auto' },
      { moveSan: 'Ke6', explanation: 'Our king follows, maintaining the wall.', playedBy: 'user' },
      { moveSan: 'Kc7', explanation: 'Black tries to escape.', playedBy: 'auto' },
      { moveSan: 'Bc6', explanation: 'The bishop seals the diagonal, preventing escape and directing the king toward a8.', playedBy: 'user' },
      { moveSan: 'Kb8', explanation: 'Black approaches the correct corner.', playedBy: 'auto' },
      { moveSan: 'Kd7', explanation: 'Follow with the king — maintain maximum restriction.', playedBy: 'user' },
      { moveSan: 'Ka7', explanation: 'Getting closer to a8.', playedBy: 'auto' },
      { moveSan: 'Kc7', explanation: 'Cut off the 7th rank — the king is almost trapped in the corner.', playedBy: 'user' },
      { moveSan: 'Ka8', explanation: 'The king reaches a8 — the correct corner for our light-squared bishop.', playedBy: 'auto' },
      { moveSan: 'Nb5', explanation: 'The knight takes up position controlling a7 — the last escape square.', playedBy: 'user' },
      { moveSan: 'Kb8', explanation: 'Forced to b8.', playedBy: 'auto' },
      { moveSan: 'Ba4', explanation: 'The bishop repositions to deliver the final blow on the key diagonal.', playedBy: 'user' },
      { moveSan: 'Ka8', explanation: 'Back in the corner.', playedBy: 'auto' },
      { moveSan: 'Bc6+', explanation: 'Check on the long diagonal.', playedBy: 'user' },
      { moveSan: 'Kb8', explanation: 'Forced.', playedBy: 'auto' },
      { moveSan: 'Na7', explanation: 'The knight hops to a7 — checkmate is now unavoidable.', playedBy: 'user' },
      { moveSan: 'Ka8', explanation: 'Forced back.', playedBy: 'auto' },
      { moveSan: 'Bd5#', explanation: 'Checkmate! The bishop delivers mate on the diagonal while the knight and king control all escape squares.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'Checkmate can ONLY be forced in a corner matching the bishop\'s square color',
      'Three phases: drive to edge, redirect to correct corner, deliver mate',
      'The W-maneuver redirects the king from the wrong corner to the correct one',
      'All three pieces must coordinate — losing any piece\'s participation lets the king escape',
      'Must complete within the 50-move rule (forced mate in at most 33 moves)',
      'Practice this endgame specifically — even grandmasters have failed it in tournaments',
    ],
  },

  {
    id: 'king-pawn-vs-king',
    kind: 'endgame',
    name: 'King + Pawn vs King',
    category: 'Essential Checkmates',
    difficulty: 'beginner',
    description:
      'Arguably the most important endgame to understand, because pawn endgames occur in almost every game. The key concept is "lead, don\'t push" — your king should advance AHEAD of the pawn, not behind it. Winning depends on reaching key squares (specific squares two ranks ahead of the pawn) and using opposition to outmaneuver the defending king. Rook pawns (a/h files) have special drawing tendencies due to stalemate tricks.',
    startingFen: '8/8/4k3/8/4P3/4K3/8/8 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'Kf4', explanation: '"Lead, don\'t push." Advance the king AHEAD of the pawn. The king needs to reach the key squares (d6, e6, or f6) for this e4 pawn.', playedBy: 'user' },
      { moveSan: 'Kd6', explanation: 'Black takes opposition on d6, trying to block the advance.', playedBy: 'auto' },
      { moveSan: 'e5', explanation: 'With Black on d6 blocking our king\'s path, we push the pawn to gain space. Now the key squares shift.', playedBy: 'user' },
      { moveSan: 'Ke6', explanation: 'Black maintains the blockade directly in front of the pawn.', playedBy: 'auto' },
      { moveSan: 'Ke4', explanation: 'We cannot advance — this position is a draw with correct defense because Black has the opposition. This teaches the critical lesson: the king must lead.', playedBy: 'user' },
      { moveSan: 'Kd6', explanation: 'Black holds the opposition and the draw.', playedBy: 'auto' },
      { moveSan: 'Kd4', explanation: 'We try to outflank, but Black mirrors.', playedBy: 'user' },
      { moveSan: 'Ke7', explanation: 'Black stays in front of the pawn — the golden rule of defense.', playedBy: 'auto' },
      { moveSan: 'Kd5', explanation: 'Advance the king. From d5 we threaten to reach the 6th rank.', playedBy: 'user' },
      { moveSan: 'Ke8', explanation: 'Black backs up but maintains the ability to oppose.', playedBy: 'auto' },
      { moveSan: 'Kd6', explanation: 'We reach d6 — a key square! With the king on the 6th rank, we have excellent winning chances.', playedBy: 'user' },
      { moveSan: 'Ke8', explanation: 'Black must step aside.', playedBy: 'auto' },
      { moveSan: 'e6', explanation: 'NOW push — the king is on the 6th rank and in front of the pawn. Two of the three winning conditions are met.', playedBy: 'user' },
      { moveSan: 'Kd8', explanation: 'Black retreats.', playedBy: 'auto' },
      { moveSan: 'e7+', explanation: 'The pawn advances with check, gaining a critical tempo.', playedBy: 'user' },
      { moveSan: 'Ke8', explanation: 'Forced to block.', playedBy: 'auto' },
      { moveSan: 'Ke6', explanation: 'Stalemate trap! If Kd6? instead, it\'s stalemate (Black has no moves). By playing Ke6, we give Black the move Kd7 or Kf7, then we promote.', playedBy: 'user' },
    ],
    keyPrinciples: [
      '"Lead, don\'t push" — the king should advance AHEAD of the pawn, not behind it',
      'Key squares: for pawns on ranks 2-4, the three squares TWO ranks ahead of the pawn',
      'Opposition: when kings face off with one square between them, the player NOT to move has the advantage',
      'Three winning conditions: king in front, has opposition, king on 6th rank — need at least two',
      'Rook pawns (a/h files) often draw even when winning conditions are met due to stalemate',
    ],
  },

  // ---------------------------------------------------------------------------
  // PAWN ENDGAMES
  // ---------------------------------------------------------------------------
  {
    id: 'opposition-direct',
    kind: 'endgame',
    name: 'Opposition (Direct)',
    category: 'Pawn Endgames',
    difficulty: 'beginner',
    description:
      'Opposition is when two kings face each other with one square between them on the same rank or file. The player NOT to move "has the opposition" — the other player must retreat or step aside, yielding control of key squares. This is the most fundamental king maneuver in endgames. Opposition is a MEANS to reach key squares, not an end in itself.',
    startingFen: '8/8/4k3/8/4K3/8/4P3/8 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'Ke5', explanation: 'Not e3 or e4 — we advance the king aggressively. Black must respond.', playedBy: 'user' },
      { moveSan: 'Ke7', explanation: 'Black tries to maintain opposition by keeping the kings face-to-face on the same file.', playedBy: 'auto' },
      { moveSan: 'Kd5', explanation: 'Sidestep! Instead of pushing the pawn, outflank the defending king. If Black mirrors with Kd7, we play Ke5.', playedBy: 'user' },
      { moveSan: 'Kd7', explanation: 'Black mirrors, maintaining the face-off.', playedBy: 'auto' },
      { moveSan: 'e4', explanation: 'Now push the pawn. Black must deal with the pawn advance while we prepare to seize the key squares (d6/e6/f6).', playedBy: 'user' },
      { moveSan: 'Ke7', explanation: 'Black returns to block the e-file.', playedBy: 'auto' },
      { moveSan: 'Ke5', explanation: 'Take the opposition! Kings face off on e5 vs e7 with one square between them. It\'s Black\'s turn — so WE have the opposition.', playedBy: 'user' },
      { moveSan: 'Kd7', explanation: 'Black must step aside — that\'s the power of opposition. The player who must move loses ground.', playedBy: 'auto' },
      { moveSan: 'Kf6', explanation: 'Penetrate! With Black on d7, we seize f6 — a KEY SQUARE for the e4 pawn. From here, the pawn promotes by force.', playedBy: 'user' },
      { moveSan: 'Ke8', explanation: 'Black tries to stay near the promotion square.', playedBy: 'auto' },
      { moveSan: 'Ke6', explanation: 'Opposition again on the 6th rank — two winning conditions met (king in front + 6th rank). The pawn will promote.', playedBy: 'user' },
      { moveSan: 'Kd8', explanation: 'Forced aside.', playedBy: 'auto' },
      { moveSan: 'e5', explanation: 'Now push — with the king on e6 leading the way, the pawn marches to promotion.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'The player NOT to move has the opposition — the other must yield ground',
      'Direct opposition: kings on same rank or file, exactly one square apart',
      'Opposition is a tool to reach key squares, not a goal in itself',
      'When the opponent takes opposition, outflank by sidestepping — don\'t push the pawn prematurely',
      'Distant opposition (odd number of squares apart) can be converted to direct opposition by mirroring',
    ],
  },

  {
    id: 'key-squares',
    kind: 'endgame',
    name: 'Key Squares',
    category: 'Pawn Endgames',
    difficulty: 'beginner',
    description:
      'Key squares (also called critical squares) are specific squares such that if the attacking king reaches one, the pawn promotes by force regardless of the defending king\'s position or whose turn it is. For pawns on ranks 2-4, the key squares are the three squares two ranks ahead of the pawn. Knowing these squares turns complex calculation into simple navigation — just get your king to a key square.',
    startingFen: '8/8/8/8/4P3/8/5K2/3k4 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'Ke3', explanation: 'Head toward the key squares. For the e4 pawn, the key squares are d6, e6, and f6. Our king must navigate there.', playedBy: 'user' },
      { moveSan: 'Ke1', explanation: 'Black tries to stay near the center.', playedBy: 'auto' },
      { moveSan: 'Kd4', explanation: 'Continue marching toward the key squares. The king leads — the pawn follows later.', playedBy: 'user' },
      { moveSan: 'Kd2', explanation: 'Black trails behind.', playedBy: 'auto' },
      { moveSan: 'Kd5', explanation: 'One step from the key squares. Black cannot catch up.', playedBy: 'user' },
      { moveSan: 'Kd3', explanation: 'Black follows but is too far behind.', playedBy: 'auto' },
      { moveSan: 'Kd6', explanation: 'Key square reached! D6 is a key square for the e4 pawn. From here, the pawn promotes by force no matter what Black does.', playedBy: 'user' },
      { moveSan: 'Ke3', explanation: 'Black chases but it\'s too late.', playedBy: 'auto' },
      { moveSan: 'e5', explanation: 'Now push the pawn. The king on d6 escorts it forward.', playedBy: 'user' },
      { moveSan: 'Ke4', explanation: 'Black approaches but can\'t stop promotion.', playedBy: 'auto' },
      { moveSan: 'e6', explanation: 'The pawn advances — the king on d6 protects e7.', playedBy: 'user' },
      { moveSan: 'Kd4', explanation: 'Black can\'t block the promotion path.', playedBy: 'auto' },
      { moveSan: 'e7', explanation: 'One square from promotion.', playedBy: 'user' },
      { moveSan: 'Kd3', explanation: 'Helpless.', playedBy: 'auto' },
      { moveSan: 'e8=Q', explanation: 'Promoted! Once the king reached a key square, promotion was inevitable.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'Key squares for pawns on ranks 2-4: three squares TWO ranks ahead of the pawn',
      'Key squares for rank 5-6 pawns: six squares spanning two ranks ahead',
      'If the attacking king reaches any key square, the pawn promotes by force',
      'Rook pawns (a/h files) have only TWO key squares — that\'s why they\'re hard to promote',
      'Navigate the king to key squares first, then push the pawn',
    ],
  },

  {
    id: 'rule-of-the-square',
    kind: 'endgame',
    name: 'Rule of the Square',
    category: 'Pawn Endgames',
    difficulty: 'beginner',
    description:
      'A quick visual calculation to determine whether a king can catch a passed pawn. Draw an imaginary square with one corner on the pawn and the opposite corner on the promotion square. If the defending king can step inside this square on their turn, they catch the pawn. If not, the pawn queens. This eliminates the need to calculate move-by-move — one glance tells you the answer.',
    startingFen: '8/8/8/1k6/8/8/7P/4K3 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'h4', explanation: 'Push the h-pawn two squares (allowed from the starting rank). The "square" now runs from h4 to h8 to d8 to d4. Black\'s king on b5 is inside this square — it CAN catch the pawn.', playedBy: 'user' },
      { moveSan: 'Kc4', explanation: 'Black enters the square and chases the pawn. With each move, Black gets closer to the pawn\'s path.', playedBy: 'auto' },
      { moveSan: 'h5', explanation: 'Push again. The square shrinks to h5-h8-e8-e5. Black is still inside.', playedBy: 'user' },
      { moveSan: 'Kd5', explanation: 'Black stays in the shrinking square, heading to intercept.', playedBy: 'auto' },
      { moveSan: 'h6', explanation: 'The square is now h6-h8-f8-f6. Black on d5 is still inside — the king will catch it.', playedBy: 'user' },
      { moveSan: 'Ke6', explanation: 'Black enters the pawn\'s file, within catching distance.', playedBy: 'auto' },
      { moveSan: 'h7', explanation: 'One more push. The square is just h7-h8-g8-g7. Black on e6 can reach g7 or g8 in time.', playedBy: 'user' },
      { moveSan: 'Kf7', explanation: 'Black catches the pawn! The king arrives in front of the pawn, stopping promotion. This confirms the rule of the square prediction.', playedBy: 'auto' },
    ],
    keyPrinciples: [
      'Draw a square from the pawn to its promotion square — if the defending king can enter, it catches the pawn',
      'Remember the pawn\'s double first move — it makes the effective square one file smaller',
      'The square shrinks by one file/rank with each pawn advance',
      'Obstacles (other pieces) can block the king\'s path even if it\'s "inside" the square',
      'This is a visual shortcut — one glance replaces complex move-by-move calculation',
    ],
  },

  {
    id: 'outside-passed-pawn',
    kind: 'endgame',
    name: 'Outside Passed Pawn',
    category: 'Pawn Endgames',
    difficulty: 'intermediate',
    description:
      'An outside passed pawn is a passed pawn far from the main pawn action, positioned on the opposite side of the board. It wins because it acts as a decoy — the defending king MUST chase it (or it promotes), but doing so abandons the defense of the other pawns. The attacking king then captures the undefended pawns. "An outside passed pawn is worth more than its material value because it functions as a deflection device."',
    startingFen: '8/pp3k2/8/PP3K2/8/8/8/8 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'a6', explanation: 'Push the outside passed pawn! This is the decoy — Black\'s king MUST respond or the a-pawn promotes.', playedBy: 'user' },
      { moveSan: 'bxa6', explanation: 'Black captures, but this opens the b-file for our b-pawn. Either way, the decoy is working.', playedBy: 'auto' },
      { moveSan: 'b6', explanation: 'The b-pawn advances, now a dangerous passed pawn. Black\'s king must race to stop it.', playedBy: 'user' },
      { moveSan: 'Ke7', explanation: 'Black heads toward the queenside to stop the pawn, abandoning the kingside.', playedBy: 'auto' },
      { moveSan: 'b7', explanation: 'Push! The b-pawn is one square from promotion. Black\'s king must reach it immediately.', playedBy: 'user' },
      { moveSan: 'Kd7', explanation: 'Rushing toward b8 to stop the pawn.', playedBy: 'auto' },
      { moveSan: 'Ke5', explanation: 'THIS is the point. While Black chases the outside passed pawn, our king marches to the kingside to gobble up the undefended a-pawn. The decoy worked.', playedBy: 'user' },
      { moveSan: 'Kc7', explanation: 'Black must capture the b-pawn.', playedBy: 'auto' },
      { moveSan: 'Kd5', explanation: 'Our king continues heading toward Black\'s a6 pawn. Black\'s king is stuck on the queenside dealing with the b-pawn.', playedBy: 'user' },
      { moveSan: 'Kxb7', explanation: 'Black captures the b-pawn, but our king is now free to harvest.', playedBy: 'auto' },
      { moveSan: 'Kc5', explanation: 'Head toward the a6 pawn. Black\'s king on b7 is too far away to defend both flanks.', playedBy: 'user' },
      { moveSan: 'Kb6', explanation: 'Black tries to protect a6.', playedBy: 'auto' },
      { moveSan: 'Kb4', explanation: 'Outflank — the king approaches a5 to capture the a-pawn.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'The outside passed pawn acts as a decoy — it pulls the defending king away from the other pawns',
      'Push the outside pawn aggressively — the THREAT of promotion is the weapon',
      'Once the defending king chases the decoy, sprint your king to the opposite side',
      'The side with the outside passed pawn wins the resulting king race',
      'Sometimes the threat of promotion is more valuable than promotion itself',
    ],
  },

  {
    id: 'protected-passed-pawn',
    kind: 'endgame',
    name: 'Protected Passed Pawn',
    category: 'Pawn Endgames',
    difficulty: 'intermediate',
    description:
      'A protected passed pawn is a passed pawn defended by another pawn. It cannot be captured without losing material, and it ties down the defending king permanently. The attacking king is free to roam the board while the defender is stuck babysitting the protected passer. Connected passed pawns on adjacent files — "the steamroller" — are especially powerful as they protect each other while advancing.',
    startingFen: '8/5k2/8/3PP3/8/5K2/8/8 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'Ke4', explanation: 'Centralize the king. The d5-e5 pawn duo is a powerful connected pair — whichever one advances, the other protects it.', playedBy: 'user' },
      { moveSan: 'Ke7', explanation: 'Black tries to blockade in front of the pawns.', playedBy: 'auto' },
      { moveSan: 'd6+', explanation: 'Push the d-pawn. If Black captures (exd6), e6 creates a protected passed pawn on e6. If Black doesn\'t capture, d6 is protected by e5.', playedBy: 'user' },
      { moveSan: 'Kd7', explanation: 'Black blocks the d-pawn.', playedBy: 'auto' },
      { moveSan: 'Kd5', explanation: 'Advance the king to support the pawn chain. The d6 pawn is protected by e5, so Black\'s king is tied down.', playedBy: 'user' },
      { moveSan: 'Ke8', explanation: 'Black retreats, but must stay close to the passed pawns.', playedBy: 'auto' },
      { moveSan: 'Ke6', explanation: 'Our king penetrates to the 6th rank. Black cannot leave — the d-pawn would promote.', playedBy: 'user' },
      { moveSan: 'Kd8', explanation: 'Black oscillates, completely tied down.', playedBy: 'auto' },
      { moveSan: 'd7', explanation: 'Push to the 7th rank. The d-pawn is still protected by e5 via the e6 square control. Black is in zugzwang.', playedBy: 'user' },
      { moveSan: 'Kc7', explanation: 'Black tries to go around.', playedBy: 'auto' },
      { moveSan: 'Ke7', explanation: 'Escort the pawn. The king supports d8=Q next move.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'A protected passed pawn ties down the defending king — it can never leave',
      'The attacking king is FREE to roam while the defender babysits',
      'Connected passed pawns protect each other as they advance ("the steamroller")',
      'Best defense is early blockade — once the pawns are advanced and protected, the burden is enormous',
      'The protected passed pawn acts as a permanent anchor restricting the opponent',
    ],
  },

  {
    id: 'pawn-breakthrough',
    kind: 'endgame',
    name: 'Pawn Breakthrough',
    category: 'Pawn Endgames',
    difficulty: 'intermediate',
    description:
      'A pawn breakthrough is a tactical sacrifice that creates a passed pawn by force, even when the pawn structure looks completely locked. The key pattern: with three pawns vs three in a locked structure, sacrifice the MIDDLE pawn. Whichever way the opponent captures, one of your remaining pawns breaks through. Timing is critical — execute only when the defending king is too far away to help.',
    startingFen: '8/8/p1p1p3/P1P1P3/8/k7/8/K7 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'c6', explanation: 'Sacrifice the middle pawn! This is the breakthrough. Black must capture one way or the other, and either way one of our pawns promotes.', playedBy: 'user' },
      { moveSan: 'bxc6', explanation: 'Black captures toward the a-file. But now the e-pawn is unblocked...', playedBy: 'auto' },
      { moveSan: 'e6', explanation: 'Push! The e-pawn races toward promotion. Black\'s d6 pawn cannot catch it, and the a-pawn covers b7.', playedBy: 'user' },
      { moveSan: 'c5', explanation: 'Black pushes but it\'s a step behind.', playedBy: 'auto' },
      { moveSan: 'e7', explanation: 'The e-pawn reaches the 7th rank. Nothing can stop it.', playedBy: 'user' },
      { moveSan: 'c4', explanation: 'Too slow — Black\'s pawn is only on the 4th rank.', playedBy: 'auto' },
      { moveSan: 'e8=Q', explanation: 'Promoted! The middle-pawn sacrifice created a fork — whichever way Black captured, one of our wing pawns broke through. If Black had played ...exd6 instead, a6! would have won on the other side.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'Sacrifice the MIDDLE pawn to create a fork — the opponent can\'t capture on both sides',
      'Whichever direction the opponent captures, the opposite-side pawn breaks through',
      'Timing is critical — the defending king must be too far away to catch the passed pawn',
      'Works with three pawns vs three in a locked structure',
      'The defender\'s remaining pawn is always one tempo too slow',
    ],
  },

  {
    id: 'zugzwang',
    kind: 'endgame',
    name: 'Zugzwang',
    category: 'Pawn Endgames',
    difficulty: 'intermediate',
    description:
      'Zugzwang (German: "compulsion to move") is a position where the obligation to make a move is a DISADVANTAGE. Any legal move worsens the position. This concept appears constantly in endgames — many positions are won only because the defender is forced to move. Recognizing and creating zugzwang positions is a core endgame skill. The "trebuchet" is a mutual zugzwang where whoever moves loses.',
    startingFen: '8/8/8/3k4/3P4/3K4/8/8 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'Ke3', explanation: 'Step aside. We cannot make progress directly (Kc4 allows Kc6 with opposition). The idea is to maneuver our king to a position where Black faces zugzwang.', playedBy: 'user' },
      { moveSan: 'Ke6', explanation: 'Black stays near the pawn.', playedBy: 'auto' },
      { moveSan: 'Ke4', explanation: 'Now we control e4 and threaten to push d5+.', playedBy: 'user' },
      { moveSan: 'Kd6', explanation: 'Black blocks the pawn.', playedBy: 'auto' },
      { moveSan: 'd5', explanation: 'Push the pawn. Now Black must decide — step aside and let our king advance, or stay and get pushed back.', playedBy: 'user' },
      { moveSan: 'Kd7', explanation: 'Black stays in front of the pawn.', playedBy: 'auto' },
      { moveSan: 'Ke5', explanation: 'Our king advances. We have two of the three winning conditions: king in front and on the 5th rank.', playedBy: 'user' },
      { moveSan: 'Kd8', explanation: 'Black retreats to d8.', playedBy: 'auto' },
      { moveSan: 'Kd6', explanation: 'THIS is zugzwang! Black must move, but every legal move loses. Kc8 allows Ke7 followed by d6-d7-d8=Q. Ke8 allows d6 with the same result. The compulsion to move is the losing factor.', playedBy: 'user' },
      { moveSan: 'Ke8', explanation: 'Forced — and now the pawn marches.', playedBy: 'auto' },
      { moveSan: 'd6', explanation: 'The pawn advances. Black\'s king has been pushed back by zugzwang, and now cannot stop promotion.', playedBy: 'user' },
      { moveSan: 'Kd8', explanation: 'Trying to block.', playedBy: 'auto' },
      { moveSan: 'd7', explanation: 'One square from promotion. Black is helpless.', playedBy: 'user' },
      { moveSan: 'Kc7', explanation: 'Forced to step aside.', playedBy: 'auto' },
      { moveSan: 'Ke7', explanation: 'Support the promotion square. d8=Q next move.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'Zugzwang: the obligation to move is a disadvantage — any move worsens the position',
      'Many endgames can ONLY be won by putting the opponent in zugzwang',
      'When you have your opponent in zugzwang, don\'t make an aggressive move that releases the pressure',
      'The trebuchet is a mutual zugzwang — whoever moves loses',
      'Recognizing zugzwang requires thinking about "what if the opponent could pass?"',
    ],
  },

  {
    id: 'triangulation',
    kind: 'endgame',
    name: 'Triangulation',
    category: 'Pawn Endgames',
    difficulty: 'intermediate',
    description:
      'Triangulation is a maneuver where the king uses three moves to return to the same square, effectively "losing a tempo" to transfer the move to the opponent. It works because the attacking king has access to three squares in a triangle, while the defending king only has two. After the triangle, the same position arises but with the opponent to move — creating zugzwang.',
    startingFen: '8/3k4/8/3PK3/8/8/8/8 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'Kd4', explanation: 'Begin the triangle. Our king can use three squares — e5, d5, d4 — forming a triangle. Black\'s king only has two useful squares (d7 and d8).', playedBy: 'user' },
      { moveSan: 'Kd8', explanation: 'Black has only two squares to oscillate between (d7 and d8).', playedBy: 'auto' },
      { moveSan: 'Kd3', explanation: 'The key move — take the "extra" triangle square. We go d4-d3 which Black cannot mirror because the king has no third square.', playedBy: 'user' },
      { moveSan: 'Kd7', explanation: 'Black is forced back to d7.', playedBy: 'auto' },
      { moveSan: 'Ke4', explanation: 'Now head back toward e5. After Kd4-Kd3-Ke4-Ke5, we\'ve used four moves to return — but Black only had two squares, so the turn has flipped.', playedBy: 'user' },
      { moveSan: 'Kd8', explanation: 'Black goes to d8 again.', playedBy: 'auto' },
      { moveSan: 'Ke5', explanation: 'We\'re back to the starting position — but now it\'s Black to move. Triangulation complete! Black is in zugzwang.', playedBy: 'user' },
      { moveSan: 'Kd7', explanation: 'Black must move and any move gives ground.', playedBy: 'auto' },
      { moveSan: 'd6', explanation: 'Push the pawn with tempo — Black must give way. The triangulation created the zugzwang we needed.', playedBy: 'user' },
      { moveSan: 'Kd8', explanation: 'Retreating.', playedBy: 'auto' },
      { moveSan: 'Kd5', explanation: 'Advance the king to support the pawn from behind.', playedBy: 'user' },
      { moveSan: 'Kd7', explanation: 'Trying to block again.', playedBy: 'auto' },
      { moveSan: 'Kc5', explanation: 'Outflank — the king goes around the pawn.', playedBy: 'user' },
      { moveSan: 'Kd8', explanation: 'Black retreats.', playedBy: 'auto' },
      { moveSan: 'Kc6', explanation: 'Key square reached! The pawn promotes by force from here.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'The attacking king uses three squares (a triangle) while the defending king only has two',
      'After the triangulation, the same position arises but with the opponent to move — creating zugzwang',
      'Triangulation is the TOOL to create zugzwang when direct advance doesn\'t work',
      'Knights cannot triangulate — they always change square color with each move',
      'Only use triangulation when a direct approach leads to a draw',
    ],
  },

  // ---------------------------------------------------------------------------
  // ROOK ENDGAMES
  // ---------------------------------------------------------------------------
  {
    id: 'lucena-position',
    kind: 'endgame',
    name: 'Lucena Position (The Bridge)',
    category: 'Rook Endgames',
    difficulty: 'intermediate',
    description:
      'The most important winning position in rook endgames. White has a pawn on the 7th rank with the king on the promotion square. The problem: Black\'s rook gives perpetual checks from behind. The solution is the "bridge" — use your rook to interpose on the 4th rank, blocking all future checks. The rook on the 4th rank is far enough away that the interposition is permanent. Does NOT work with rook pawns.',
    startingFen: '1K1k4/1P6/8/8/8/8/r7/2R5 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'Rd1+', explanation: 'Check the king away! We need to get our king off the promotion square so the pawn can promote, but first the enemy king must step aside.', playedBy: 'user' },
      { moveSan: 'Ke7', explanation: 'Forced away from blocking the king\'s exit.', playedBy: 'auto' },
      { moveSan: 'Kc7', explanation: 'The king emerges from behind the pawn. Now Black will try perpetual checks from behind.', playedBy: 'user' },
      { moveSan: 'Rc2+', explanation: 'Here come the checks! Black\'s rook hammers from behind. Without the bridge technique, these checks are perpetual.', playedBy: 'auto' },
      { moveSan: 'Kd6', explanation: 'Step toward the center, heading away from the pawn. Each check drives us closer to the bridge.', playedBy: 'user' },
      { moveSan: 'Rd2+', explanation: 'Another check from behind.', playedBy: 'auto' },
      { moveSan: 'Ke6', explanation: 'Keep advancing. One more step to set up the bridge.', playedBy: 'user' },
      { moveSan: 'Re2+', explanation: 'Still checking.', playedBy: 'auto' },
      { moveSan: 'Kf5', explanation: 'Almost there — one more check and we build the bridge.', playedBy: 'user' },
      { moveSan: 'Rf2+', explanation: 'The checks continue, but we\'re in position now.', playedBy: 'auto' },
      { moveSan: 'Rd4', explanation: 'THE BRIDGE! The rook interposes on the 4th rank, blocking ALL future checks along the file. Black\'s rook cannot check without losing itself. The pawn promotes next move.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'First: check the enemy king away from blocking your king\'s exit',
      'Then: march your king away from the pawn while absorbing checks',
      'Build the bridge: place your rook on the 4th rank to permanently block checks',
      'The 4th rank is the critical distance — closer and the checks continue',
      'Does NOT work with rook pawns (a/h files)',
    ],
  },

  {
    id: 'philidor-position',
    kind: 'endgame',
    name: 'Philidor Position (Drawing Technique)',
    category: 'Rook Endgames',
    difficulty: 'intermediate',
    description:
      'The most important drawing technique in rook endgames. As the defender, place your rook on the 3rd rank (the 6th rank from the attacker\'s view) to prevent the enemy king from advancing. Hold this position until the pawn reaches the 6th rank, then immediately switch the rook to the back rank for perpetual checks from behind. The key: the rook must be far enough away (3+ files) for effective checking distance.',
    startingFen: '3k4/8/3KP3/8/8/r7/8/4R3 b - - 0 1',
    userColor: 'b',
    mainLine: [
      { moveSan: 'Ra6', explanation: 'Phase 1: Third-rank defense. The rook on the 6th rank (3rd from Black\'s view) prevents the white king from advancing to e7. HOLD this position — don\'t move the rook until the pawn pushes to the 6th rank.', playedBy: 'user' },
      { moveSan: 'Rd1', explanation: 'White repositions, trying to advance.', playedBy: 'auto' },
      { moveSan: 'Ra5', explanation: 'Maintain the defense. The rook stays active, keeping the white king at bay.', playedBy: 'user' },
      { moveSan: 'e7', explanation: 'White pushes the pawn to the 7th rank, hoping to break through.', playedBy: 'auto' },
      { moveSan: 'Ra1', explanation: 'Phase 2: IMMEDIATELY switch to the back rank! The moment the pawn advances past the 6th rank, the rook goes behind for perpetual checks. Timing is critical — wait too long and the king shelters.', playedBy: 'user' },
      { moveSan: 'Rd3', explanation: 'White tries to shield the king from checks.', playedBy: 'auto' },
      { moveSan: 'Rd1', explanation: 'Attack the rook — with the pawn on e7, the king cannot come to e8, and checks from behind are devastating.', playedBy: 'user' },
      { moveSan: 'Rc3', explanation: 'White tries to escape the checks.', playedBy: 'auto' },
      { moveSan: 'Ke8', explanation: 'Capture the pawn if it promotes, or hold the position. The white king cannot simultaneously support the pawn and escape the checks.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'Phase 1: Rook on the 3rd rank (6th from attacker) — prevents the enemy king from advancing',
      'HOLD the third-rank defense until the pawn reaches the 6th rank',
      'Phase 2: The INSTANT the pawn advances to the 6th rank, switch the rook to the back rank',
      'From the back rank, deliver perpetual checks — the king cannot escape without abandoning the pawn',
      'The rook needs checking distance of at least 3 files to be effective',
    ],
  },

  {
    id: 'tarraschs-rule',
    kind: 'endgame',
    name: 'Tarrasch\'s Rule (Rook Behind Passed Pawn)',
    category: 'Rook Endgames',
    difficulty: 'intermediate',
    description:
      '"Rooks belong behind passed pawns" — whether they are YOUR pawns or your OPPONENT\'s. Behind your own passed pawn: as the pawn advances, the rook\'s scope INCREASES (each step forward opens a new square). Behind the opponent\'s passed pawn: the rook restricts the pawn and its scope increases as the pawn advances. In front of a passed pawn: the rook gets progressively more cramped as the pawn advances.',
    startingFen: '8/3k4/8/3P4/8/8/8/R2K4 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'Kd2', explanation: 'Advance the king while the rook stays behind the d-pawn. From a1, the rook supports every square the pawn will cross.', playedBy: 'user' },
      { moveSan: 'Kd6', explanation: 'Black blocks the pawn.', playedBy: 'auto' },
      { moveSan: 'Kd3', explanation: 'Continue marching the king. The rook needs no repositioning — from behind the pawn, it already supports the entire advance.', playedBy: 'user' },
      { moveSan: 'Kd7', explanation: 'Black stays in front.', playedBy: 'auto' },
      { moveSan: 'Kd4', explanation: 'The king escorts the pawn forward. Notice the rook on a1 controls the entire d-file from behind — maximum scope.', playedBy: 'user' },
      { moveSan: 'Kd6', explanation: 'Black blocks again.', playedBy: 'auto' },
      { moveSan: 'Ra6+', explanation: 'Use the rook actively! Check drives the king away from the blockade square.', playedBy: 'user' },
      { moveSan: 'Kd7', explanation: 'Black retreats.', playedBy: 'auto' },
      { moveSan: 'd6', explanation: 'Push! The rook on a6 still supports the pawn from behind along the 6th rank, and can return to the d-file at any time.', playedBy: 'user' },
      { moveSan: 'Ke8', explanation: 'Black retreats further.', playedBy: 'auto' },
      { moveSan: 'Kd5', explanation: 'The king advances. The pawn is well-supported and the rook\'s activity from behind is enormous.', playedBy: 'user' },
      { moveSan: 'Kd8', explanation: 'Black tries to stay close.', playedBy: 'auto' },
      { moveSan: 'Ra8+', explanation: 'Drive the king away from the promotion square with a check from behind.', playedBy: 'user' },
      { moveSan: 'Ke7', explanation: 'Forced aside.', playedBy: 'auto' },
      { moveSan: 'd7', explanation: 'The pawn reaches the 7th rank. Rd8 threatens promotion. The rook behind the passed pawn has been effective throughout.', playedBy: 'user' },
    ],
    keyPrinciples: [
      '"Rooks belong behind passed pawns" — your own AND your opponent\'s',
      'Behind your pawn: rook scope INCREASES as the pawn advances',
      'Behind the opponent\'s pawn: the rook restricts it and gains scope as it advances',
      'In FRONT of a pawn: the rook gets progressively more cramped — avoid this',
      'This applies to both attacking and defending in rook endgames',
    ],
  },

  {
    id: 'active-vs-passive-rook',
    kind: 'endgame',
    name: 'Active vs Passive Rook',
    category: 'Rook Endgames',
    difficulty: 'intermediate',
    description:
      'An active rook (attacking pawns, controlling ranks/files, creating threats) is worth significantly more than a passive rook tied to defense. In rook endgames, piece activity is often more important than material. Sacrificing a pawn to activate a passive rook is frequently the correct decision — the activity more than compensates for the lost material.',
    startingFen: '8/R4pk1/5p2/5P2/8/6K1/8/5r2 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'Ra6', explanation: 'Keep the rook ACTIVE. On the 6th rank, our rook attacks the f6 pawn and controls the entire rank. An active rook creates threats the opponent must constantly respond to.', playedBy: 'user' },
      { moveSan: 'Rb1', explanation: 'Black\'s rook enters behind our position, but our active rook is more dangerous.', playedBy: 'auto' },
      { moveSan: 'Rxf6', explanation: 'Capture the weak pawn! Our active rook picks off material while Black\'s rook has no targets.', playedBy: 'user' },
      { moveSan: 'Rb5', explanation: 'Black attacks our f5 pawn. Now both rooks are active.', playedBy: 'auto' },
      { moveSan: 'Rf7+', explanation: 'Stay active! The rook on the 7th rank is incredibly powerful — it attacks the g7 pawn and confines Black\'s king to the back rank.', playedBy: 'user' },
      { moveSan: 'Kg8', explanation: 'The king is trapped on the back rank by our rook on the 7th.', playedBy: 'auto' },
      { moveSan: 'Kg4', explanation: 'Advance the king while the rook dominates. Black\'s rook is forced to defend passively.', playedBy: 'user' },
      { moveSan: 'Rxf5', explanation: 'Black takes the pawn, but our rook on the 7th is worth more than a pawn.', playedBy: 'auto' },
      { moveSan: 'Rxg7+', explanation: 'Harvest another pawn from the 7th rank! The active rook on the 7th dominates.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'An active rook (attacking, threatening) vastly outperforms a passive rook (defending, restricted)',
      'Sacrificing a pawn to activate a passive rook is often correct',
      'Rook activity matters more than material in most rook endgames',
      'Ways to activate: occupy open files, reach the 7th rank, attack weak pawns',
      'If your rook is passive, trade it off or sacrifice material to free it',
    ],
  },

  {
    id: 'rook-on-the-7th-rank',
    kind: 'endgame',
    name: 'Rook on the 7th Rank',
    category: 'Rook Endgames',
    difficulty: 'intermediate',
    description:
      'A rook on the 7th rank is one of the most powerful placements in chess. It attacks all unadvanced pawns (most start on the 2nd rank), traps the enemy king on the back rank, and creates mating threats. "A rook on the seventh rank is often considered sufficient compensation for a pawn." Two rooks on the 7th — "pigs on the 7th" — are often immediately decisive.',
    startingFen: '6k1/R4ppp/8/8/8/8/5PPP/6K1 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'Kf1', explanation: 'First, secure our own king. The rook on a7 already dominates — it attacks f7 and confines Black\'s king to the 8th rank. No rush.', playedBy: 'user' },
      { moveSan: 'Kh8', explanation: 'Black\'s king is trapped on the back rank! It cannot come to f8 or e8 because the rook controls the entire 7th rank.', playedBy: 'auto' },
      { moveSan: 'Ke2', explanation: 'Centralize the king. With Black\'s king trapped, we can improve at leisure. This is the "do not rush" principle in action.', playedBy: 'user' },
      { moveSan: 'Kg8', explanation: 'Black shuffles — there\'s nothing constructive to do with the king trapped on the back rank.', playedBy: 'auto' },
      { moveSan: 'Kd3', explanation: 'Continue advancing. The rook on the 7th does the heavy lifting — tying down Black\'s entire position.', playedBy: 'user' },
      { moveSan: 'Kh8', explanation: 'Still trapped.', playedBy: 'auto' },
      { moveSan: 'Ke4', explanation: 'The king marches to support the attack. Black\'s f7/g7/h7 pawns are all under fire.', playedBy: 'user' },
      { moveSan: 'Kg8', explanation: 'Black can only shuttle the king.', playedBy: 'auto' },
      { moveSan: 'Kf5', explanation: 'The king arrives to support the rook\'s attack on the weakened pawns.', playedBy: 'user' },
      { moveSan: 'Kh8', explanation: 'Passive defense.', playedBy: 'auto' },
      { moveSan: 'Kg6', explanation: 'Threaten to capture f7, g7, and h7 pawns with king and rook cooperation.', playedBy: 'user' },
      { moveSan: 'Kg8', explanation: 'Forced — must defend f7.', playedBy: 'auto' },
      { moveSan: 'Rxf7', explanation: 'The first pawn falls to the rook on the 7th. With the king on g6, the remaining pawns will follow.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'The rook on the 7th attacks all unadvanced pawns simultaneously',
      'The enemy king is confined to the back rank — it cannot participate in the game',
      'Sufficient compensation for a pawn in many positions',
      'Combine with king advancement to create an overwhelming attack',
      '"Two rooks on the 7th" (pigs on the 7th) are usually immediately decisive',
    ],
  },

  // ---------------------------------------------------------------------------
  // MINOR PIECE ENDGAMES
  // ---------------------------------------------------------------------------
  {
    id: 'bishop-vs-knight-open',
    kind: 'endgame',
    name: 'Bishop vs Knight (Open Position)',
    category: 'Minor Piece Endgames',
    difficulty: 'intermediate',
    description:
      'In open positions with pawns on both sides of the board, the bishop dominates the knight. The bishop is a long-range piece that can influence both flanks simultaneously from a single diagonal. The knight is short-range — it "can exert control over only one part of the board at a time and often takes multiple moves to reposition." When action spans both wings, the bishop\'s range is decisive.',
    startingFen: '8/pp3k2/4b3/8/8/5N2/PP3K2/8 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'Nd4', explanation: 'Centralize the knight — in open positions, the knight needs a secure outpost. From d4, it controls key squares on both sides.', playedBy: 'user' },
      { moveSan: 'Bc4', explanation: 'The bishop takes a long diagonal, simultaneously eyeing the queenside and kingside. This illustrates the bishop\'s advantage — one move covers both wings.', playedBy: 'auto' },
      { moveSan: 'Ke3', explanation: 'Centralize the king. In the endgame, the king is a fighting piece.', playedBy: 'user' },
      { moveSan: 'Ke7', explanation: 'Black centralizes as well.', playedBy: 'auto' },
      { moveSan: 'Nf5+', explanation: 'Use the knight actively — check gains a tempo. But notice the knight had to physically travel to create this threat.', playedBy: 'user' },
      { moveSan: 'Kd6', explanation: 'Black sidesteps.', playedBy: 'auto' },
      { moveSan: 'Kd4', explanation: 'Advance the king while the knight holds the position.', playedBy: 'user' },
      { moveSan: 'Bf1', explanation: 'The bishop retreats to f1 — but from here it still controls the long diagonal. The bishop lost no time because it works at long range.', playedBy: 'auto' },
      { moveSan: 'Ne3', explanation: 'Reposition the knight to target the kingside. Notice this takes two moves — the knight is slow to reposition compared to the bishop.', playedBy: 'user' },
      { moveSan: 'Bc4', explanation: 'The bishop instantly covers both sides again. This is the core asymmetry — the bishop repositions in one move while the knight needs several.', playedBy: 'auto' },
      { moveSan: 'b3', explanation: 'Fix our pawns on the opposite color from the enemy bishop. Pawns on light squares are safe from the dark-squared bishop.', playedBy: 'user' },
      { moveSan: 'Be2', explanation: 'The bishop shifts effortlessly to the other diagonal.', playedBy: 'auto' },
      { moveSan: 'Nc2', explanation: 'The knight must slowly reposition. In open positions with action on both sides, this slowness is a significant disadvantage.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'Bishop dominates knight in OPEN positions with pawns on both sides of the board',
      'The bishop covers the whole board from one diagonal — the knight must physically walk to each wing',
      'Knight is better in CLOSED positions where it can jump over blocked pawns',
      'Place your pawns on the opposite color from the enemy bishop',
      'Before entering an endgame, evaluate the pawn structure — open favors bishop, closed favors knight',
    ],
  },

  {
    id: 'good-bishop-vs-bad-bishop',
    kind: 'endgame',
    name: 'Good Bishop vs Bad Bishop',
    category: 'Minor Piece Endgames',
    difficulty: 'intermediate',
    description:
      'A "good" bishop has its pawns on the OPPOSITE color — its diagonals are free. A "bad" bishop has pawns on the SAME color — blocked by its own pieces, it does little more than a pawn (sometimes called a "tall pawn"). The strategic goal: place your pawns on the opposite color from your bishop, and try to fix the opponent\'s pawns on their bishop\'s color.',
    startingFen: '8/p4k2/1p6/2p1B3/8/5K2/PP6/8 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'Ke4', explanation: 'Centralize the king. Our bishop on e5 is GOOD — our pawns are on a2/b2 (dark squares), leaving the light-square diagonals wide open for the bishop.', playedBy: 'user' },
      { moveSan: 'Ke7', explanation: 'Black tries to centralize, but the pawns on a7/b6/c5 are fixed on dark squares — restricting their own bishop if they had one.', playedBy: 'auto' },
      { moveSan: 'Kd5', explanation: 'Our king penetrates to d5. The bishop on e5 controls dark squares while the king dominates the center.', playedBy: 'user' },
      { moveSan: 'Kd7', explanation: 'Black tries to oppose but the king is cramped.', playedBy: 'auto' },
      { moveSan: 'Bd6', explanation: 'The bishop seizes d6, cutting off the black king. Notice how freely our bishop moves — no friendly pawns are blocking its diagonals.', playedBy: 'user' },
      { moveSan: 'Kc8', explanation: 'Black retreats.', playedBy: 'auto' },
      { moveSan: 'Kc6', explanation: 'Our king advances to c6, threatening to march to b7 and capture the a-pawn.', playedBy: 'user' },
      { moveSan: 'Kb8', explanation: 'Black defends the a-pawn.', playedBy: 'auto' },
      { moveSan: 'b4', explanation: 'Open a second front on the queenside. The bishop is free on dark squares while b4 creates threats on the light squares.', playedBy: 'user' },
      { moveSan: 'cxb4', explanation: 'Black captures.', playedBy: 'auto' },
      { moveSan: 'Bxb4', explanation: 'Recapture with the bishop, which remains active. Now we threaten a4-a5 creating a passed pawn.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'Good bishop: pawns on OPPOSITE color — diagonals are clear',
      'Bad bishop: pawns on SAME color — blocked by own pawns, a "tall pawn"',
      'Place YOUR pawns on the opposite color from your bishop',
      'Fix the OPPONENT\'s pawns on their bishop\'s color to restrict it',
      'A bad bishop can still be useful defensively — don\'t automatically trade it',
    ],
  },

  {
    id: 'opposite-colored-bishops',
    kind: 'endgame',
    name: 'Opposite-Colored Bishops',
    category: 'Minor Piece Endgames',
    difficulty: 'advanced',
    description:
      'When each side has a bishop on opposite colors (one light-squared, one dark-squared), the position has extreme drawing tendencies. Each bishop controls only half the board and literally cannot attack the opponent\'s bishop or the pawns it defends. Even two extra pawns draws about 50% of the time. Cecil Purdy: "In endings with bishops of opposite color, material means NOTHING, position EVERYTHING." The defender places pawns on their bishop\'s color for an impregnable fortress.',
    startingFen: '8/p4k2/4b3/8/3P4/2B5/P4K2/8 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'd5', explanation: 'Push the passed pawn. With an extra pawn, White tries to win — but opposite-colored bishops make this extremely difficult.', playedBy: 'user' },
      { moveSan: 'Bd7', explanation: 'Black places the bishop where it can monitor the d-file. The bishop will blockade the passed pawn on a square our bishop cannot attack.', playedBy: 'auto' },
      { moveSan: 'Ke3', explanation: 'Advance the king to support the pawn.', playedBy: 'user' },
      { moveSan: 'Ke7', explanation: 'Black\'s king heads toward the pawn, ready to blockade.', playedBy: 'auto' },
      { moveSan: 'Kd4', explanation: 'We push forward, but Black\'s light-squared bishop controls squares our dark-squared bishop cannot reach.', playedBy: 'user' },
      { moveSan: 'Kd6', explanation: 'Black blockades! The king sits in front of the pawn on d6. Our bishop on c3 cannot attack d6 (a light square).', playedBy: 'auto' },
      { moveSan: 'Be5+', explanation: 'Try to dislodge the blockade with a check.', playedBy: 'user' },
      { moveSan: 'Kc5', explanation: 'Black steps aside but maintains blockade potential.', playedBy: 'auto' },
      { moveSan: 'd6', explanation: 'Push the pawn while the king is off d6.', playedBy: 'user' },
      { moveSan: 'Be6', explanation: 'The bishop controls d7 from e6 — a light square our dark-squared bishop can never contest. This is WHY opposite-colored bishops draw: the defending bishop operates on squares the attacking bishop cannot influence.', playedBy: 'auto' },
      { moveSan: 'Ke4', explanation: 'We try to maneuver, but the fortress holds.', playedBy: 'user' },
      { moveSan: 'Kd5', explanation: 'Black\'s king returns to blockade. The draw is nearly certain — our bishop cannot break through on the wrong color complex.', playedBy: 'auto' },
    ],
    keyPrinciples: [
      'Extreme drawing tendencies — each bishop controls only half the board',
      'The defending bishop operates on squares the attacking bishop can never reach',
      'Even two extra pawns draws about 50% of the time',
      'If you\'re ahead in material, AVOID trading into opposite-colored bishops',
      'If you\'re behind, SEEK opposite-colored bishops — they\'re your best drawing chance',
      'Exception: with major pieces still on the board, opposite colors FAVOR the attacker',
    ],
  },

  {
    id: 'knight-endgame-fundamentals',
    kind: 'endgame',
    name: 'Knight Endgame Fundamentals',
    category: 'Minor Piece Endgames',
    difficulty: 'advanced',
    description:
      'Knight endgames play more like pawn endgames than bishop endgames. The key reason: knights cannot lose a tempo (they change square color every move), which means they cannot triangulate or "wait." This makes zugzwang a constant threat, just like in pure pawn endgames. Outside passed pawns are decisive because the short-range knight must physically travel to address threats on both sides of the board.',
    startingFen: '8/pp2nk2/8/2N3p1/6P1/8/PP3K2/8 w - - 0 1',
    userColor: 'w',
    mainLine: [
      { moveSan: 'Ke3', explanation: 'Centralize the king. In knight endgames (like pawn endgames), the king is a critical fighting piece.', playedBy: 'user' },
      { moveSan: 'Ke6', explanation: 'Black centralizes too.', playedBy: 'auto' },
      { moveSan: 'Kd4', explanation: 'Advance toward the center. Our knight on c5 is well-placed, attacking b7 and controlling key central squares.', playedBy: 'user' },
      { moveSan: 'Kd6', explanation: 'Black opposes our king.', playedBy: 'auto' },
      { moveSan: 'Nb3', explanation: 'Reposition the knight. Notice it takes two moves minimum to reach a new theater — unlike a bishop that can cross the board in one move. This is why outside passed pawns are so strong against knights.', playedBy: 'user' },
      { moveSan: 'Nc6', explanation: 'Black\'s knight goes to c6, trying to blockade the b-pawn.', playedBy: 'auto' },
      { moveSan: 'a3', explanation: 'Prepare b4 to create a passed pawn. In knight endgames, outside passed pawns are decisive — the knight can\'t cover both flanks.', playedBy: 'user' },
      { moveSan: 'Nb4', explanation: 'Black tries to blockade but the knight can only be in one place at a time.', playedBy: 'auto' },
      { moveSan: 'Nc5', explanation: 'Attack b7 again. The knight jumps back — but notice every repositioning takes multiple moves. Knights are short-range pieces.', playedBy: 'user' },
      { moveSan: 'Nc6', explanation: 'Black defends b7 while blocking the c-file.', playedBy: 'auto' },
      { moveSan: 'Nxb7+', explanation: 'Capture the pawn! Now we create an outside passed pawn on the b-file.', playedBy: 'user' },
      { moveSan: 'Kc7', explanation: 'Black chases the knight, but our king is free.', playedBy: 'auto' },
      { moveSan: 'Na5', explanation: 'The knight retreats but our position is winning — the outside passed pawn on the b-file will force Black\'s knight to chase it while our king attacks the g5 pawn.', playedBy: 'user' },
    ],
    keyPrinciples: [
      'Knight endgames resemble PAWN endgames — zugzwang is a constant threat',
      'Knights cannot lose a tempo (they change square color every move) — no triangulation possible',
      'Outside passed pawns are decisive — the short-range knight can\'t cover both flanks',
      'Knights are slow to reposition — multiple moves to travel to a new theater',
      'Two knights don\'t cooperate well (unlike two bishops) — they cover similar squares',
    ],
  },
];
